# Ordered roots for the bounded Fil-C world package cohort.
# Keep foundational libraries and userland ahead of the desktop landmarks.
[
  # Base userland and developer tools
  "bash"
  "coreutils"
  "gnumake"
  "gnum4"
  "bison"
  "gawk"
  "gnused"
  "gnugrep"
  "lesspipe"
  "flex"
  "bc"
  "ed"
  "which"
  "file"
  "diffutils"
  "gnutar"
  "bzip2"
  "zstd"
  "xz"
  "util-linux"
  "procps"
  "inetutils"
  "elfutils"
  "strace"
  "ncurses"
  "tmux"
  "nano"
  "nethack"
  "figlet"
  "clolcat"
  "pkgconf"
  "autoconf"
  "automake"
  "libtool"
  "git"
  "curl"
  "openssh"
  "openssl"
  "sqlite"
  "lua"
  "perl"
  "tcl"

  # Widely reused native libraries and protocol foundations
  "zlib"
  "expat"
  "libffi"
  "pcre2"
  "libxml2"
  "libpng"
  "libjpeg_turbo"
  "freetype"
  "fontconfig"
  "harfbuzz"
  "cairo"
  "glib"
  "libevent"
  "libuv"
  "icu78"
  "fmt"
  "quickjs"
  "dbus"
  "libsoup_3"

  # Wayland and GTK/GObject desktop landmarks
  "wayland"
  "wayland-protocols"
  "libxkbcommon"
  "libdrm"
  "libinput"
  "at-spi2-core"
  "gobject-introspection-unwrapped"
  "gdk-pixbuf"
  "pango"
  "gtk3"
  "gtk4"
  "gtksourceview3"
  "gtksourceview4"

  # Real language runtimes and interactive applications
  "python312"
  "ruby_3_3"
  "emacs30"
  "trealla"
  "lighttpd"
  "kittydoom"

  # Larger optional closures should not starve the core landmarks above.
  "gtkmm4"
  "ffmpeg-headless"
]
