// Round-trip messages generated by protoc through the Fil-C protobuf runtime.
#include <cstdio>
#include <cstdlib>
#include <string>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
#include <google/protobuf/text_format.h>
#include <google/protobuf/util/message_differencer.h>
#include <google/protobuf/util/json_util.h>

#include "protobuf.pb.h"

#define CHECK(cond)                                                    \
  do {                                                                 \
    if (!(cond)) {                                                     \
      std::fprintf(stderr, "%s:%d: check failed: %s\n", __FILE__,      \
                   __LINE__, #cond);                                   \
      std::exit(1);                                                    \
    }                                                                  \
  } while (0)

using filnix::test::Alternating;
using filnix::test::Shape;

static Shape MakeShape() {
  Shape s;
  s.set_name("triangle");
  for (int i = 0; i < 3; i++) {
    auto* p = s.add_points();
    p->set_x(i * 10);
    p->set_y(-i);
    p->set_label("p" + std::to_string(i));
  }
  (*s.mutable_tags())["sides"] = 3;
  (*s.mutable_tags())["big"] = 1LL << 40;
  s.set_blob(std::string("\0\1\2\377", 4));
  Shape* child = s.mutable_child();
  child->set_name("inner");
  child->set_radius(2.5);
  return s;
}

// Map entries are otherwise serialized in hash order.
static std::string Serialize(const google::protobuf::Message& m) {
  std::string out;
  {
    google::protobuf::io::StringOutputStream stream(&out);
    google::protobuf::io::CodedOutputStream coded(&stream);
    coded.SetSerializationDeterministic(true);
    CHECK(m.SerializeToCodedStream(&coded));
  }
  return out;
}

static void AppendVarint(std::string& out, uint64_t v) {
  while (v >= 0x80) {
    out.push_back(static_cast<char>(v | 0x80));
    v >>= 7;
  }
  out.push_back(static_cast<char>(v));
}

int main() {
  // Binary round trip.
  Shape s = MakeShape();
  std::string wire = Serialize(s);
  Shape t;
  CHECK(t.ParseFromString(wire));
  CHECK(t.name() == "triangle");
  CHECK(t.points_size() == 3);
  CHECK(t.points(2).x() == 20 && t.points(2).y() == -2);
  CHECK(t.points(1).label() == "p1");
  CHECK(t.tags().at("big") == (1LL << 40));
  CHECK(t.blob() == std::string("\0\1\2\377", 4));
  CHECK(t.has_child() && t.child().radius() == 2.5);
  CHECK(Serialize(t) == wire);
  CHECK(google::protobuf::util::MessageDifferencer::Equals(s, t));

  // Text format round trip.
  std::string text;
  CHECK(google::protobuf::TextFormat::PrintToString(s, &text));
  Shape u;
  CHECK(google::protobuf::TextFormat::ParseFromString(text, &u));
  CHECK(Serialize(u) == wire);

  // JSON round trip, and an error with a message (a heap-allocated status).
  std::string json;
  CHECK(google::protobuf::util::MessageToJsonString(s, &json).ok());
  Shape v;
  CHECK(google::protobuf::util::JsonStringToMessage(json, &v).ok());
  CHECK(Serialize(v) == wire);
  auto status = google::protobuf::util::JsonStringToMessage(
      "{\"name\": 42, \"nope\": true}", &v);
  CHECK(!status.ok());
  // absl::string_view in current releases, StringPiece in 3.21.
  std::string message(status.message().data(), status.message().size());
  CHECK(!message.empty());
  std::printf("expected JSON error: %s\n", message.c_str());

  // A large message whose fields alternate on the wire. With tail calls that
  // are not real tail calls, every field would add a stack frame.
  const int n = 1000000;
  std::string alt;
  for (int i = 0; i < n; i++) {
    alt.push_back(0x08);  // field 1, varint
    AppendVarint(alt, i);
    alt.push_back(0x12);  // field 2, length-delimited
    alt.push_back(1);
    alt.push_back('a' + i % 26);
  }
  Alternating a;
  CHECK(a.ParseFromString(alt));
  CHECK(a.a_size() == n && a.b_size() == n);
  CHECK(a.a(n - 1) == n - 1 && a.b(27) == "b");

  std::printf("ok: %zu-byte shape, %zu-byte alternating message\n",
              wire.size(), alt.size());
  return 0;
}
