# Round-trip messages generated by protoc through Fil-C Python's protobuf.
import sys
from google.protobuf import json_format, text_format
from google.protobuf.internal import api_implementation
from google.protobuf import descriptor_pb2, timestamp_pb2
import protobuf_pb2 as pb

assert api_implementation.Type() == "python", api_implementation.Type()
assert "google._upb._message" not in sys.modules

s = pb.Shape(name="triangle", blob=b"\0\1\2\377")
for i in range(3):
    s.points.add(x=i * 10, y=-i, label="p%d" % i)
s.tags["sides"] = 3
s.tags["big"] = 1 << 40
s.child.name = "inner"
s.child.radius = 2.5

wire = s.SerializeToString(deterministic=True)
t = pb.Shape.FromString(wire)
assert t == s and t.points[2].x == 20 and t.tags["big"] == 1 << 40
assert t.WhichOneof("kind") == "child" and t.child.radius == 2.5
assert text_format.Parse(text_format.MessageToString(s), pb.Shape()) == s
assert json_format.Parse(json_format.MessageToJson(s), pb.Shape()) == s
try:
    json_format.Parse('{"name": 42}', pb.Shape())
    raise AssertionError("bad JSON accepted")
except json_format.ParseError as e:
    print("expected JSON error:", e)

# A larger message with repeated fields.
n = 20000
a = pb.Alternating()
a.a.extend(range(n))
a.b.extend(chr(97 + i % 26) for i in range(n))
b = pb.Alternating.FromString(a.SerializeToString())
assert list(b.a) == list(range(n)) and b.b[27] == "b"

# Descriptors of the well-known types go through the same code paths.
fds = descriptor_pb2.FileDescriptorProto()
descriptor_pb2.DESCRIPTOR.CopyToProto(fds)
assert descriptor_pb2.FileDescriptorProto.FromString(fds.SerializeToString()) == fds
ts = timestamp_pb2.Timestamp(seconds=1700000000, nanos=5)
assert json_format.Parse(json_format.MessageToJson(ts), timestamp_pb2.Timestamp()) == ts

print("ok: %d-byte shape, backend %s" % (len(wire), api_implementation.Type()))
